# Pokemon Red Agent Comparison - Environment Setup
# Environment configuration for conda

name: pokemon-red-comparison
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.10.18
  - pip>=22.0
  
  # Core scientific computing
  - numpy>=1.21.0
  - pandas>=1.3.0
  - matplotlib>=3.4.0
  - scipy>=1.7.0
  - scikit-learn>=1.0.0
  - scikit-image>=0.18.0
  
  # Deep Learning
  - pytorch>=1.12.0
  - pytorch-cuda=11.8  # Compatible with Python 3.10
  - cudatoolkit=11.8   # If GPU available
  
  # Visualization
  - seaborn>=0.11.0
  - plotly>=5.0.0
  
  # Development tools
  - jupyter
  - ipython>=7.0.0
  - tqdm
  
  # Utilities
  - pyyaml>=6.0
  - packaging
  - pillow>=8.3.0
  
  # Dependencies via pip (not available in conda)
  - pip:
    - pyboy>=2.0.0
    - gymnasium>=0.26.0
    - stable-baselines3>=1.6.0,<2.0.0
    - mediapy>=1.1.0
    - einops>=0.4.0
    - PySDL2>=0.9.0
    - pysdl2-dll>=2.0.0
    - websockets>=10.0,<14.0
    - tensorboard>=2.8.0,<3.0.0
    - cloudpickle>=2.0.0,<4.0.0
    - filelock>=3.0.0
    - python-dateutil>=2.8.0
    - grpcio>=1.40.0,<2.0.0